apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: gcp-devops-dep
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: gcp
  template: 
    metadata:
      labels: 
        app: gcp
    spec: 
      containers:
      - name: gcp-devops-dep
        image: gcr.io/superb-memory-454612-u9/gcpdevops:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"